using HeartLog.SimpleDbTool.Enum;

namespace HeartLog.SimpleDbTool.Attribute
{/// <summary>
 /// 列名特性
 /// </summary>
    public class ColumnAttribute : System.Attribute
    {
        /// <summary>
        /// 对应的数据库表列名
        /// </summary>
        public string ColumnName;

        /// <summary>
        /// 是否为自增主键
        /// </summary>
        public bool IsAutoGeneratedKey = false;

        /// <summary>
        /// 是否为主键
        /// </summary>
        public bool IsPrimaryKey;
        /// <summary>
        /// 列的数据类型
        /// </summary>
        public ColumnType ColumnType;

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="columnName"></param>
        public ColumnAttribute(string columnName)
        {
            ColumnName = columnName;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="columnName">columnName</param>
        /// <param name="columnType">columnType</param>
        public ColumnAttribute(string columnName, ColumnType columnType)
        {
            ColumnName = columnName;
            ColumnType = columnType;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="columnName">对应的数据库表列名</param>
        /// <param name="isAutoGeneratedKey">是否是自增主键</param>
        /// <param name="columnType">列的数据类型</param>
        public ColumnAttribute(string columnName, bool isAutoGeneratedKey, ColumnType columnType)
        {
            ColumnName = columnName;
            IsAutoGeneratedKey = isAutoGeneratedKey;
            ColumnType = columnType;
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="columnName">对应的数据库表列名</param>
        /// <param name="isAutoGeneratedKey">是否是自增主键</param>
        /// <param name="isPrimaryKey">是否是主键</param>
        /// <param name="columnType">列的数据类型</param>
        public ColumnAttribute(string columnName, bool isAutoGeneratedKey, bool isPrimaryKey, ColumnType columnType)
        {
            ColumnName = columnName;
            IsPrimaryKey = isPrimaryKey;
            IsAutoGeneratedKey = isAutoGeneratedKey;
            ColumnType = columnType;
        }
    }
}
